### PR TITLE
added text inside command.json file

### PR DESCRIPTION
**Pull request by rushigithub12**
clear branch-1

### CODE REVIEW

**Comment by rushigithub12** [comment]
created one branch and raised pull request

**Comment by mentor-tara** [comment]
Looks like something is wrong :astonished:	Please see the CI checks below for more information. Click the "Details" link for more information as shown in this screenshot.

Screenshot of CI checks[](error)

**Comment by rushigithub12** [comment]
clear branch-1

**Comment by mentor-tara** [comment]
Looks like something is wrong :astonished:	Please see the CI checks below for more information. Click the "Details" link for more information as shown in this screenshot.

Screenshot of CI checks[](error)

**Comment by rushigithub12** [comment]
closing PR

**Pull request closed without merging**
